---

driver                    :
    name                  : <%= if ENV['TRAVIS'] then 'localhost' else 'vagrant' end  %>
    box                   : "ubuntu/trusty64"
    customize             :
         cpus             : 2
         memory           : 2048

verifier                  :
  name                    : serverspec
  remote_exec             : false

provisioner:
    name                  : ansible_push
    verbose               : "vvvv"
    ansible_config        : "test/ansible.cfg"
    ansible_playbook_bin  : "ansible-playbook"
    idempotency_test      : True
    diff                  : True
    sudo                  : <%= if ENV['TRAVIS'] then 'True' else 'False' end  %>
    raw_arguments         : <%= if ENV['TRAVIS'] then '-c local' else '' end %>
    extra_vars            : { 'kitchen_connection': '<%= if ENV["TRAVIS"] then "local" else "smart" end %>', 'kitchen_hosts': '<%= if ENV["TRAVIS"] then "localhost" else "all" end %>' }
    use_instance_name     : true
    groups                :
         rabbitmq-cluster :
                            - "cluster1.192.168.110.10.xip.io"
                            - "cluster2.192.168.110.20.xip.io"
#                            - "cluster-3-docker-u14"
platforms:
 - name                   : docker-u14
   driver_config          :
     image                : quay.io/hellofresh/kitchen-base
     platform             : ubuntu
   driver                 :
    name                  : docker
    socket                : unix:///var/run/docker.sock
    use_sudo              : false

suites                    :
  - name                  : standalone
    provisioner           :
        playbook          : "test/integration/standalone/standalone.yml"
    verifier              :
      patterns            : [ test/integration/standalone/serverspec/*_spec.rb ]

  - name                  : cluster1
    provisioner           :
        playbook          : "test/integration/cluster_1/cluster_1.yml"
        inventory_hostname: cluster1.192.168.110.10.xip.io
    verifier              :
      patterns            : [ test/integration/cluster_1/serverspec/*_spec.rb ]
    driver_config         :
      run_options         : "--net cluster_network --ip=192.168.110.10"
      publish_all         : true
      hostname            : cluster1
      instance_name       : cluster1
      # links               :
      #                       - "cluster_2:cluster_2"
      #                       - "cluster_3:cluster_3"

  - name                  : cluster2.192.168.110.20.xip.io
    provisioner           :
        playbook          : "test/integration/cluster_2/cluster_2.yml"
        inventory_hostname: cluster2.192.168.120.10.xip.io
    verifier              :
      patterns            : [ test/integration/cluster_2/serverspec/*_spec.rb ]
    driver_config         :
      run_options         : "--net cluster_network --ip=192.168.110.20"
      publish_all         : true
      hostname            : cluster2
      instance_name       : cluster2
      # links               :
      #                       - "cluster_1:cluster_1"
      #                       - "cluster_3:cluster_3"

  - name                  : cluster3
    provisioner           :
        playbook          : "test/integration/cluster_3/cluster_3.yml"
    verifier              :
      patterns            : [ test/integration/cluster_3/serverspec/*_spec.rb ]
    driver_config         :
      instance_name       : cluster3
      publish_all         : true
      # links               :
      #                       - "cluster_1:cluster_1"
      #                       - "cluster_2:cluster_2"

