---
# Erlang stuff
- name: add erlang repo key
  apt_key:
    url: https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc
    state: present

- name: add erlang repo
  apt_repository:
    repo: deb http://dl.bintray.com/rabbitmq/debian xenial erlang-20.x
    state: present
    update_cache: yes

# RabbitMQ official install
- name: "add the official rabbitmq repository's key"
  apt_key: url=https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x6B73A36E6026DFCA
  when: not rabbitmq_os_package

- name: add the official rabbitmq repository
  copy:
    src=rabbitmq.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo
  when: not rabbitmq_os_package

- name: install rabbitmq-server
  apt: name=rabbitmq-server update_cache=yes

- name: enable rabbitmq-server to survive reboot
  service: name=rabbitmq-server enabled=yes
