---
# handlers file for rabbitmq

- name: reload systemd
  command: systemctl daemon-reload

- name: restart rabbitmq-server
  service: name=rabbitmq-server state=restarted enabled=yes

- name: stop rabbitmq-server
  service: name=rabbitmq-server state=stopped enabled=yes

- name: start rabbitmq-server
  service: name=rabbitmq-server state=started enabled=yes
